name: "buildxy"
description: ""
inputs:
  container_name:
    description: Name of your container, i.e. `mycoolname/container`
    required: true
  container_tag:
    description: Tag for your container, i.e. `latest` - omit to make one up based on the branch name
    required: false
  mode:
    description: Set to `push` to push your contianer (and the cache manifest), or `build` to just build it"
    required: false
    default: build
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    BUILDXY_MODE: ${{ inputs.mode }}
    CONTAINER_NAME: ${{ inputs.container_name }}
    CONTAINER_TAG: ${{ inputs.container_tag }}
