on:
  pull_request:
    branches:
      - main

name: Build buildxy

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to container registry
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: buildxy
        uses: ./
        with:
          container_name: docker.io/jordemort/buildxy
